### ISSUE TITLE
Transformation link in space

### ISSUE THREAD

**Issue by skoehnen** [HumanBrainProject/openMINDS_SANDS#20]

**Comment by lzehl** [comment]
Pending at the moment. Should be part of the discussion for "coordinateSpace.schema.json" #40 
Also, it was decided that "transformation" will be handled as an activity, meaning as a "protocol" / "protocolExecution" via openMINDS.

**Comment by lzehl** [comment]
for now it was decided that this will be handle via the protocol / protocolExecution. I'll close this issue for now
