### ISSUE TITLE
schema-revision: core/anatomicalEntity.schema.json

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#26]
1. delete `performedBy`? 
    * not needed, because implicitly clear through source and/or annotation I think
    * anatomicalEntity "just" represents the name/term of an annotation can be either drawn from:
      * a known source (user-defined annotation is named after an anatomicalEntity from a known atlas)
      * or custom made (user-defined annotation is named with a user-defined anatomicalEntity)
      * or atlas defined (known atlas annotation is named with corresponding atlas anatomicalEntity)
2. make `source` optional
    * if there is no source the anatomicalEntity name is user-defined
4. source should expect `brainAtlas` or `terminology` ? 
3. note: `parentStructure` has to have the same source
    * necessary requirement to mirror a (atlas) terminology (and its hierarchy)

**Comment by lzehl** [comment]
point-01:
@aeidi89 : if it's relatively easy to add properties again, we could leave out all provenance related properties. question would come back to the point if provenance is useful here (in the purpose of SANDS).
@UlrikeS91 : also in openMINDS provenance is not really covered. 
-> leave it out

point-02:
@aeidi89 : always be able to point to an ontology, but how is that technically done?
-> source should link to terminology
-> terminology links to atlas
-> each schema atlas, terminology as well as anatomicalEntity get a relatedOntology property (link to individual ontology IDs)
-> source should allow multiple entries, and optional (note: required for being connected to an atlas)

point-03:
s.above

point-04: 
@UlrikeS91 + @aeidi89 agrees
also considering parentStructure:
@aeidi89 : considering hierarchies by connecting anatomicalEntities - is it possible to define an additional hierarchy to what is captured in the terminology of a specific atlas? Potential use case: highlight similarities of neighbouring regions based on new hierarchy. 
@lzehl : I think this is a nice feature but should not be considered as the ground truth of SANDS; goal of SANDS: capture the atlas structures as they were published. New adoption of these atlas structures should be considered as new datasets. (@aeidi89 + @UlrikeS91 agrees with this)

**Comment by lzehl** [comment]
@UlrikeS91 & @aeidi89 : please comment on the following as soon as you can!

I'm currently generating example JSON-LDs for the Julich-Brain Atlas (v2.0), as test instances for the atlas viewer team.  

I'm struggling with `laterality` being a property of the *anatomicalEntity.schema.json*, because I have to make four JSON-LDs per region (2 anatomicalEntities + 2 annotations) to unambiguously connect them to the corresponding file instances that hold only the annotation of one hemisphere...  
Schematic outline:
- hOc1_left (anatomicalEntity) -> hOc1_left (annotation) -> hOc1_left (file instance)
- hOc1_right (anatomicalEntity) -> hOc1_right (annotation) -> hOc1_right (file instance)

If we would move `laterality` to be a property of the *annotation.schema.json*, we could only register one anatomicalEntity.  
Schematic outline: 
- hOc1 (anatomicalEntity) -> hOc1_left (annotation) -> file_hOc1 (file instance)
- hOc1 (anatomicalEntity) -> hOc1_right (annotation) -> file_hOc1 (file instance)

Another question: would you consider the probability map (pm) of a region a separate annotation than the maximum probability map (mpm) of that region? or would you define the pm as the `inspiredBy` input of the annotation, and the mpm as the `definedIn`?

**Comment by aeidi89** [comment]
Question 1, `laterality`: Moving `laterality` from _[anatomicalEntity.schema.json](https://github.com/HumanBrainProject/SANDS/wiki/SANDS-(v0.1)#anatomicalEntity)_ to _[annotation.schema.json](https://github.com/HumanBrainProject/SANDS/wiki/SANDS-(v0.1)#annotation)_ sounds logical to me.

**Comment by aeidi89** [comment]
**Question 2, pm and mpm:** given what I read in this [link](https://download.brainvoyager.com/bv/doc/UsersGuide/ProbabilisticMaps/ProbabilisticMaps.html) it sounds like pm and mpm technically are separate annotations, as they show different information. 

In the context of a reference atlas, if the mpm is what has been published, we should only consider this and ignore the pm (as this is part of the provenance in this specific case). 
In the context of a dataset where pm (and automatically mpm) have been preformed, both should be considered. 

Answer: pm and mpm are separate annotations.

**Question 3, defining `inspiredBy` and `definedIn`:** To get the correct reference here, we need to know how the pm and mpm have been aquired, is the mpm created in paralell with the pm or as a product of pm?

(I think Stefan knows the answer to this, @skoehnen )

E.g. parallel aquisition: 
YES --> inspiredBy=brainfile(s), definedIn=nativeSpace
NO -->mpm: inspiredBy=pm, definedIn=MNI
     --->pm: inspiredBy=_brain_, definedIn=nativeSpace

**Comment by lzehl** [comment]
Hi, I should have been more specific: I talk about the **pm** and **mpm** of the Julich-Brain Atlas.

The **mpm** is the definitely the product of all **pm**s for one Julich-Brain Atlas version.
From my point of view that would make the **pm**s be the `inspiredBy` for the mpm annotation.

NOTE: `definedIn` should not lead to a **coordinateSpace**, but to a or multiple **fileInstance**!
Side note: `definedIn` is actually part of **annotationFile.schema.json** which is attached to **annotation.schema.json**
For simplicity I neglected that here.

I agree on keeping the annotations for pm and mpm separate. That would mean schematically:

- annotation **pm** of one region (Julich-Brain):
  - `inpiredBy` -> not provided
  - `definedIn` -> fileInstance for single **pm**

- annotation **mpm** of one region (Julich-Brain):
  - `inpiredBy` -> all **pm**s OR the **pm** of that and all surrounding regions (@skoehnen ?)
  - `definedIn` -> fileInstance for **mpm** (here `internalFileIdentifier` is important)

**Comment by lzehl** [comment]
@UlrikeS91 we need one change here:

`source` which links to the `atlasTerminology` should be removed from this schema for two reasons:
a) `atlasTerminology` links already to `anatomicalEntity` (back link not needed)
b) `anatomicalEntity` might not be part of any `atlasTerminology`

**Comment by UlrikeS91** [comment]
> @UlrikeS91 we need one change here:
> 
> `source` which links to the `atlasTerminology` should be removed from this schema for two reasons:
> a) `atlasTerminology` links already to `anatomicalEntity` (back link not needed)
> b) `anatomicalEntity` might not be part of any `atlasTerminology`

Yes, this is true. I'll remove it. Half-related question: Did we agree on renaming terminology to atlasTerminology now? I really missed this if this has been decided on during our meeting earlier :D

**Comment by UlrikeS91** [comment]
Revisions finished.
