### ISSUE TITLE
schema-revision: core/annotation.schema.json

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#27]
1. delete `performedBy`
2. discuss linkage between `annotation` and `anatomicalEntity`
    * should be `annotation` -> `annotationToEntity` -> `anatomicalEntity`
    * why? because in principle there are three cases:
      * atlas annotation is linked to its anatomical entity / terminology term used in that atlas
      * user-defined annotation is linked to an anatomical entity of a defined atlas
      * user-defined annotation is linked to a user-defined anatomical entity
    * But do we need a full `annotationToEntity` schema or could this be defined in specific links? e.g.:
      * definingTerm: link between user-defined annotation and user-defined entity OR atlas annotation and atlas entity
      * relatedAtlasTerm: link between user-defined annotation and atlas entity
3. `criteria` and and `criteriaType` should be grouped? e.g.,:
      * criteria-schema with properties: criteriaType, protocol(execution)??
4. delete `nativeCoordinateSpace` (or explain why this is needed)
    * comes back to: is an annotation always connected to at least one annotationFile?

**Comment by UlrikeS91** [comment]
1. Agreed. 
2. I'm not a fan of `annotation` -> `annotationToEntity` -> `anatomicalEntity`. The only information it gives, is who made the connection (`performedBy`), which is again more provenance/curation progress tracking. I would prefer Lyuba's proposal with definingTerm and relatedTerm. Potentially the relatedTerm could be redundant, if we were to use `entityToEntity` on the definingTerm to establish relatedTerm(s). But I'm not sure, because I'm still missing the exact definition of `entityToEntity` (see #30).
3. Yes. I think grouping this will be nicer. 
4. Additionally, wouldn't `inspiredBy`give you similar information? If I remember correctly, this should point to the original file the annotation has been made in/from, right? That file has a native space and would also be indirectly connected to the annotation itself then. If there is no `inspiredBy`-file added, then the property could be useful. But same question as Lyuba: What is this useful for if I don't have the file that native space came from?

**Comment by aeidi89** [comment]
#37 _electrode schema_

These issues are connected, and have to be discussed in the light of eachother.

**Comment by lzehl** [comment]
This issue is highly connected to #32

**Comment by lzehl** [comment]
As a summary, here my suggestion on how to change annotation & annotationFile

- **annotation.schema.json**:
  - criteria [expects: protocol | protocolExecution, count: 1]
  - criteriaType [ expects: asserted | processive, count: 1]
  - annotationFiles [expects: annotationFile, count: 1 - N]
  - definingTerm [expects: anatomicalEntity, count: 1]
  - relatedAtlasTerm [expects: anatomicalEntity, count: 0 - N]  

[NOTE: criteria & criteriaType could also be grouped in an annotationCriteria schema]

- **annotationFile.schema.json**:
  - displayIn [expects: image, count: 1]
  - inspiredBy [expects: image, count: 0 - N]
  - displayRules [expects: displayRules, count: 1]

[NOTE: I renamed here navigationRules to displayRules]

- **displayRule.schema.json**:
  - internalFileIdentifier [expects: free text, count: 1]
  - bestViewPoint [expects: coordinate, count: 1]
  - displayColor [expects: array of numbers (items: 3), count: 0 - 1]
  
[NOTE: should be extended with a bestViewAngle property, clarification needed from the IAV team what is needed here]

**Comment by lzehl** [comment]
Based on the discussion we had I will update the following in my next PR:

    annotation.schema.json:
        criteria [expects: protocol | protocolExecution, count: 1]
        criteriaType [ expects: asserted | processive, count: 1]
        definingTerm [expects: anatomicalEntity, count: 1]
        relatedAtlasTerm [expects: anatomicalEntity, count: 0 - N]
        inspiredBy [expects: image, count: 0 - N]
        visualizedIn [expects: visualizationParameters, count: 1]

    visualizationParameters.schema.json:
        definedIn [expects: image, count: 1]
        internalFileIdentifier [expects: free text, count: 1]
        bestViewPoint [expects: coordinate, count: 1]
        displayColor [expects: array of numbers (items: 3), count: 0 - 1]

@xgui3783 what other information do you need for the visualization?
@aeidi89 & @UlrikeS91 please let me know if that fits. Latest in the PR which will follow soon.

**Comment by lzehl** [comment]
@aeidi89 we still need your feedback considering the expected entities (amount) for `definingTerm` and `relatedAtlasTerm`.
+ I guess we agree that `relatedAtlasTerm` should be optional
+ I guess we agree that `definingTerm` should be mandatory
+ should we allow more than one entry for `relatedAtlasTerm`? 
   - possible use case: user-defined annotation is related to "V1" (atlas X), "hOc1" (altas Y), "BA 17" (atlas Z)
   - possible use case: user-defined annotation is the sum of two atlas regions, e.g. V1 + V2 (atlas X)
+ should we allow more than one entry for `definingTerm`?
   - possible use case: atlas annotation is defined by two terms from two different terminology versions
   - possible use case: user-defined annotation is defined by two different term versions

@aeidi89 pleas check if the use cases make sense. If they do I suggest we allow for both `definingTerm` and `relatedAtlasTerm` multiple entries. In case of `definingTerm` the terms need to be part of terminologies that belong to the same `brainAtlas`, correct?

**Comment by xgui3783** [comment]
@lzehl from my side, I can't see anything that's urgently needed. That is to say, until we start to incoorperate into our applications and workflows, we won't find any.

I am indeed very excited about producing SANDS conforming data already in some existing applications.

**Comment by lzehl** [comment]
@xgui3783 thanks for the feedback here. We'll can add properties of course also later when we see we need them.

Happy that you're joining the SANDS development :slightly_smiling_face: I'm looking forward to test the model with you soon!

**Comment by UlrikeS91** [comment]
After discussion with @aeidi89, we conclude:

- `definingTerm`= mandatory and `relatedAtlasTerm` = optional (as you suggested)
- `definingTerm` with 1 - N seems illogical --> there shouldn't be 2 definitions for one item; either name of property is misleading or it shouldn't be several. In terms of atlases and terminology versioning, this would be a neat solution, but is it for anything else?   
- `relatedAtlasTerm` with 0 - N makes sense because it allows higher granularity (e.g. allows several regions when close to their border) with demanding high specificity BUT it also allows for high uncertainty  
- `definingTerm` with 1 makes sense
- `relatedAtlasTerm` with 0 - 1 can make sense BUT when you're at a border for two regions or you have an user-defined region that is bigger than atlas region you have to lower the granularity (by referring to the next higher region level) 

Let's allow several for both properties BUT we should think of a different name for `definingTerm` ;) 

Suggestion for new name: `namingTerm` (for simplicity's sake :D )

**Comment by UlrikeS91** [comment]
> After discussion with @aeidi89, we conclude:
> 
> * `definingTerm`= mandatory and `relatedAtlasTerm` = optional (as you suggested)
> * `definingTerm` with 1 - N seems illogical --> there shouldn't be 2 definitions for one item; either name of property is misleading or it shouldn't be several. In terms of atlases and terminology versioning, this would be a neat solution, but is it for anything else?
> * `relatedAtlasTerm` with 0 - N makes sense because it allows higher granularity (e.g. allows several regions when close to their border) with demanding high specificity BUT it also allows for high uncertainty
> * `definingTerm` with 1 makes sense
> * `relatedAtlasTerm` with 0 - 1 can make sense BUT when you're at a border for two regions or you have an user-defined region that is bigger than atlas region you have to lower the granularity (by referring to the next higher region level)
> 
> Let's allow several for both properties BUT we should think of a different name for `definingTerm` ;)
> 
> Suggestion for new name: `namingTerm` (for simplicity's sake :D )

Addentum:
Even though several `anatomicalEntities` are allow for `relatedAtlasTerm`, it should only be within one atlas and not across several. This should only give the opportunity to say that the annotation is related to several regions within one version. Across versions/atlases IS handled by ontology.
`definingTerm` can be within and across atlas versions BUT never across different atlases. Also, in case of an atlas annotation it cannot refer to several anatomicalEntitities within the same version. 

`relatedAtlasTerm`: within atlas version YES, across atlas versions NO, across different atlases NO
`definingTerm` (for non-atlas annotation): within atlas version YES, across atlas versions NO, across different atlases NO
`definingTerm` (for atlas annotation):  within atlas version NO, across atlas versions YES, across different atlases NO

**Comment by lzehl** [comment]
`relatedAtlasTerm`: within atlas version YES, across atlas versions NO, across different atlases NO
- this is very restrictive assume that everything across atlas versions and across atlases is handled via the ontology, which is especially across atlases in a lot of cases not the case right now...
- I would not be that restrictive, but we can always start like that and change to a lower restriction later if we see it doesn't work

`definingTerm` (for non-atlas annotation): within atlas version YES, across atlas versions NO, across different atlases NO
- here the phrasing is a bit wrong, if it is a non-atlas annotation it cannot be connected to an atlas term but term then is always user defined and (more or less) independent of any atlas
- here the question only arises how many we allow for one annotation and if those are actually connected to any terminology, since this is not an atlas term and I assumed terminology schema to be only used for atlases (if you agree here, we could rename this to atlasTerminology)

`definingTerm` (for atlas annotation): within atlas version NO, across atlas versions YES, across different atlases NO
- changing the property to `namingTerm` is fine with me 
- allowing only one entry makes only sense to me if a new terminology version would lead to a new atlas version in which case terminology does not have it's own version similar to annotation, because changes in both will cause to be a new brain atlas version to be defined (which is fine with me) @aeidi89 does this make sense?
  - if this is true the user will only see via the version innovation description what the cause is of the new brain atlas version (new annotations and/or new terminology and/or new referenceSpace); 
  - if this is true only in case of referenceSpace a separate version needs to be captured, because the referenceSpace might not be originating from the same project (e.g., Julich-Brain is just using the MNI spaces, but did not created them)
- otherwise the assumption to the atlases you stated here seem logical to me

**Comment by UlrikeS91** [comment]
> `relatedAtlasTerm`: within atlas version YES, across atlas versions NO, across different atlases NO
> 
> * this is very restrictive assume that everything across atlas versions and across atlases is handled via the ontology, which is especially across atlases in a lot of cases not the case right now...
> * I would not be that restrictive, but we can always start like that and change to a lower restriction later if we see it doesn't work
> 
> `definingTerm` (for non-atlas annotation): within atlas version YES, across atlas versions NO, across different atlases NO
> 
> * here the phrasing is a bit wrong, if it is a non-atlas annotation it cannot be connected to an atlas term but term then is always user defined and (more or less) independent of any atlas
> * here the question only arises how many we allow for one annotation and if those are actually connected to any terminology, since this is not an atlas term and I assumed terminology schema to be only used for atlases (if you agree here, we could rename this to atlasTerminology)
> 
> `definingTerm` (for atlas annotation): within atlas version NO, across atlas versions YES, across different atlases NO
> 
> * changing the property to `namingTerm` is fine with me
> * allowing only one entry makes only sense to me if a new terminology version would lead to a new atlas version in which case terminology does not have it's own version similar to annotation, because changes in both will cause to be a new brain atlas version to be defined (which is fine with me) @aeidi89 does this make sense?
>   
>   * if this is true the user will only see via the version innovation description what the cause is of the new brain atlas version (new annotations and/or new terminology and/or new referenceSpace);
>   * if this is true only in case of referenceSpace a separate version needs to be captured, because the referenceSpace might not be originating from the same project (e.g., Julich-Brain is just using the MNI spaces, but did not created them)
> * otherwise the assumption to the atlases you stated here seem logical to me

Conclusion from meeting for annotation schema:
Changes: 
- `alias` added
- `definingTerm` renamed to `namingTerm`
- `namingTerm` count changed from 1 to 1 - N


@UlrikeS91, implement changes to annotation schema as: 


    alias [string (free text), count: 0 -1]
    criteria [expects: protocol | protocolExecution, count: 0 - 1]
    criteriaType [ expects: asserted | processive, count: 1]
    namingTerm [expects: anatomicalEntity, count: 1 - N]
    inspiredBy [expects: image, count: 0 - N]
    laterality [expects: left | right, count: 1 - 2]
    relatedAtlasTerm [expects: anatomicalEntity, count: 0 - N]
    visualizedIn [expects: visualizationParameters, count: 1]

Action point: All version related properties need to be removed from terminology.schema.json. Related to #31. (@UlrikeS91: Add note to this issue and revise schema again)

**Comment by UlrikeS91** [comment]
Revisions finished.
