### ISSUE TITLE
schema-revision: core/entityToEntity.schema.json

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#30]
1. this should only be used between entities from different sources
2. I'm not sure if confidence should be a number, because this could also be only semantic

**Comment by UlrikeS91** [comment]
1. Agreed. 
2. Not sure if numbers will be the best, but maybe we should rather ask: How should we define the `confidence` and what should it describe? Should this be as Ingvild is doing to describe how well areas are related to each other ("identical", "overlapping", etc.)? This would mean that `entityToEntity` is more of a check how well the attached annotation reflects another with the same name from a different source (e.g. Paxinos Hippocampus to Swanson Hippocampus)?

**Comment by lzehl** [comment]
summary of what need to be done; properties:
- anatomicalEntityObject (anatomicalEntity, count 1)
- anatomicalEntitySubject (anatomicalEntity, count 1)
- relationType (controlledTerm, count 1) ["identical", "subset", "superset] (match with Ingvild's list)
- procentualOverlap (integer (0 - 100), count 0 - 1)
- confidence (controlledTerm, count 1)

**Comment by lzehl** [comment]
@UlrikeS91 based on a discussion with @olinux this schema and the anatomicalEntity.schema.json need some changes.  
Here the TODOs:

entityToEntity.schema.json
- rename to anatomicalEntityRelation.schema.json
- delete `anatomicalEntitySubject`
- rename `anatomicalEntityObject` to `inRelationTo`

anatomicalEntity.schema.json
- add property `otherAnatomicalRelations` [expects: anatomicalEntityRelation.schema.json, count: 0 - N]

@UlrikeS91 could you take this over?

**Comment by UlrikeS91** [comment]
I can do that. This makes it far easier to understand the exact relation between object and subject (which a bunch of people had problems with :D). 

I've added it to my checklist #86

**Comment by UlrikeS91** [comment]
Revisions finished.
