### ISSUE TITLE
schema-revision: core/terminology.schema.json

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#31]
1. replace `anatomicalDefinitions` wiht `anatomicalEntities`
2. can a terminology have versions that are independent of the atlas version?
    * yes -> keep the element and use it to group the corresponding entities
    * no -> delete scheman, keep it only as property of brainAtlas and directly connect to the corresponding entities

**Comment by UlrikeS91** [comment]
2. No idea... @aeidi89, could you maybe comment on this?

**Comment by UlrikeS91** [comment]
1. done

**Comment by lzehl** [comment]
@aeidi89 Could you please comment on point 2? I think we discussed it a bit and you said it can be versioned correct?

**Comment by aeidi89** [comment]
2. Yes, a terminology can be versioned.
In context of a reference brain atlas, every version of an atlas has a corresponding version of the terminology used in that atlas. In addition, that versioned terminology can be versioned further, for instance to address spelling mistakes. This should be checked with @tgbugs.

**Comment by tgbugs** [comment]
A terminology can be versioned. I usually think about a terminology as a single file in a git repo. Each version would be a different revision of the file. There are some types of changes that don't induce any changes in the actually content of the terminology, but most of the time we don't have to worry about those.

**Comment by lzehl** [comment]
- alias (1)
- anatomicalEntities (1-n)
- definedIn (minds/file | openminds/fileinstance, 0-n)
- fullName (1)
- relatedOntology (0-1)
- releaseDate (date, 1)
- versionIdentifier (1)
- newVersionOf (0-1)
- alternativeVersionOf (0-n) 
- versionInnovation (0-1)

**Comment by UlrikeS91** [comment]
Note: If agreed to proposal in #27 to rename `terminology` to `atlasTerminology`, we need to start another PR following to first revision PR to:
1) Change schema name
2) Change `"$ref"` to `...#definitions/ATLAS_TERMINOLOGY"` in `anatomicalEntity` and `brainAtlasVersion` 
3) Change definitions.json file with the changes

**Comment by lzehl** [comment]
yes! go ahead ;)

**Comment by UlrikeS91** [comment]
> yes! go ahead ;)

Okay, then I missed this conclusion :D I'll make the changes in a new PR :)

**Comment by UlrikeS91** [comment]
Revisions finished.
