### ISSUE TITLE
schema-revision: elements/coordinates.schema.json

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#33]
1. add a `definedIn` ?

**Comment by UlrikeS91** [comment]
What would be the advantage of having `definedIn` here? It could be added as an optional feature, but if there are no real advantages to this, I don't see why we should add it.

**Comment by lzehl** [comment]
I thought about it a bit more and agree. It makes much more sense to reference to the "fileInstance" where also the file internal identifier is set. Please cf. **electrodeContact** in #37

**Comment by lzehl** [comment]
double check and "release" / close this issue
+ rename schema to coordinatePoint.schema.json (correct related schemas and definitions)
+ what to do with actual coordinates:
   @xgui3783 : all three in one property as array? or in separate properties split in x, y, z ?
   @xgui3783 : do you assume / want to have coordinates in physical units or in pixel? (Note: I guess from the user perspective we will rather get physical units)

**Comment by xgui3783** [comment]
@lzehl 

> do you assume / want to have coordinates in physical units or in pixel? (Note: I guess from the user perspective we will rather get physical units)

I would have assumed this would be clear from [coordinateSpace](https://github.com/HumanBrainProject/SANDS/blob/b1de4cc/v0.1/elements/coordinates.schema.json#L25-L28) -> [axes](https://github.com/HumanBrainProject/SANDS/blob/b1de4cc8f58399b43efca61912eceb95107e7169/v0.1/core/coordinateSpace.schema.json#L47-L50) -> axes (links broken) ?

**Comment by xgui3783** [comment]
@lzehl 

> all three in one property as array? or in separate properties split in x, y, z ?

From my perspective, either makes sense, but in a lot of ways, will depend on how axes is defined?

**Comment by lzehl** [comment]
- I'm happy to stick to one property with array with values for x, y, z 
- axes links are not broken you cannot directly use them as urls though; direct urls are defined in definitions.json to reduce maintenance issues
- units are defined in axes (#35) and/or indexingParameters (#36)
- questions still remains for which property we assume the physical units or pixes/voxels or unitless values (I don't get what would be preferred where)

NOTE: controlledTerms will be vocabulary that is defined by the curation team as terminology (cf. #41)

**Comment by xgui3783** [comment]
I mean axes in definitions are broken:

```json
{
    "AXES": {
      "$id": "#options/axes",
      "$ref": "https://raw.githubusercontent.com/HumanBrainProject/SANDS/master/v0.1/elements/axes.schema.json"
    }
}
```
from <https://github.com/HumanBrainProject/SANDS/blob/b3b6612/v0.1/definitions.json#L63-L66>

but should be

```json
{
    "AXES": {
      "$id": "#options/axes",
      "$ref": "https://raw.githubusercontent.com/HumanBrainProject/SANDS/master/v0.1/options/axes.schema.json"
    }
}
```

**Comment by xgui3783** [comment]
re: physical vs pixel/voxel, it will largely depend on the coordinateSpace, no?

if the coordinateSpace is an unregistered volume/image, it is likely going to be unitless/voxel/pixel, whereas if it is a HBP supported reference space, it will likely be in physical space (mm or um)?

**Comment by lzehl** [comment]
a) the coordinateSpace does not have any resolution only the defaultImage that is connected to the coordinateSpace, correct? So number of pixels/voxels for each axes should be defined in indexingParameters or in image?
b) the coordinateSpace should define what 1 is, correct? which should be the unit stated in the axes?
c) for coordinates that means that I expect the coordinates to be delivered in the unit of the axes for the attached coordinateSpace?

**Comment by xgui3783** [comment]
> a) the coordinateSpace does not have any resolution only the defaultImage that is connected to the coordinateSpace, correct? So number of pixels/voxels for each axes should be defined in indexingParameters or in image?

I agree that coordinateSpace does not have any resolution. But at the same time, the unit of the axes associated with the coordinateSpace is not necessarily voxel/pixel, no? For Big Brain etc, for example, it **could** be mm/um (I would argue that it should be). For a non registered image/volume (e.g., histological scan), it can be either. 

> b) the coordinateSpace should define what 1 is, correct? which should be the unit stated in the axes?

I agree. The unit needs to be defined, or explicitly defined to be unitless (i.e. pixel/voxel)

> c) for coordinates that means that I expect the coordinates to be delivered in the unit of the axes for the attached coordinateSpace?

That is how I understood the schema.

**Comment by UlrikeS91** [comment]
@lzehl Can I asked why this issue has been closed? We should revise the code:

1. coordinates should have min and max Items
2. Descriptions should be added (even though not crucial)
3. $id has sand in it and not sands
4. We wanted to rename the schema to coordinatePoint (right?)

**Comment by lzehl** [comment]
I closed it because the last review went through. But you are correct. Go ahead and do the corresponding changes. 
I'll open the issue for this again.

**Comment by UlrikeS91** [comment]
Revisions finished.
