### ISSUE TITLE
schema-revision: elements/image.schema.json

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#34]
1. what is in `spacing` ? not defined yet (can't remember the purpose of this)

**Comment by lzehl** [comment]
@UlrikeS91 & @aeidi89 : could you please comment here? I think it's the only open issue in this schema.

I think `spacing` is covered with the **axes.schema.json** in combination with the **indexingParameters.schema.json**  
Am I correct?

**Comment by aeidi89** [comment]
1. What was meant with `spacing` is how far it is between 2 points (given that this is a fixed value, which I think it almost always will be). E.g. the unit of a system might be mm, but the spacing can be 1 --> 1 mm between two points, or it could be 2 --> 2 mm between two points, and so on.

I agree with you @lzehl that `spacing` could be covered by the property `steps` in the **[indexingParameters.schema.json](https://github.com/HumanBrainProject/SANDS/wiki/SANDS-(v0.1)#indexingParameters)**. 

The **[image.schema.json](https://github.com/HumanBrainProject/SANDS/wiki/SANDS-(v0.1)#image)** does not link to **indexingParameters.schema.json**, but it links to the **[axes.schema.json](https://github.com/HumanBrainProject/SANDS/wiki/SANDS-(v0.1)#axes)** which does link to the **indexingParameters.schema.json**.

**Comment by lzehl** [comment]
Yes, the connection is indirect from **image.schema.json** to **axes.schema.json** to **indexingParameters.schema.json** (reference chain).

I would say we can then delete `spacing` form **image.schema.json**. 
@UlrikeS91 let me know if you have time to update the code, or if I should put it on my list.

**Comment by lzehl** [comment]
summary of properties:
- axes (axes, count: 1)
- definedIn (file | fileInstance, count: 1)

**Comment by lzehl** [comment]
Discussion with Xiao and Stefan:
- an image has it's in intrinsic coordinate space
- for this reason the image should point also to a coordinate space
- the axes then only needs to be defined in the coordinate space
- this means though that the indexingParameters need to be placed at the image not at the axes, because it belongs to the image or actual file not the coordinate space

**Comment by lzehl** [comment]
@UlrikeS91 here we need the following changes:

    image.schema.json
        coordinateSpace [expects: coordinateSpace; count: 1]
        definedIn [expects: cscs/file|openminds/fileinstance; count: 1]
        indexingParameters [expects: indexingParameters; count: 0 - 1]

**Comment by UlrikeS91** [comment]
- delete `indexingParameters.schema.json` 
- add `voxelSize` (array of 3 numbers) and `unit`

**Comment by UlrikeS91** [comment]
Revisions finished.
