### ISSUE TITLE
schema-revision: core/coordinateSpace.schema.json

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_SANDS#40]

**Comment by lzehl** [comment]
1) in documentation `defaultImages` property points to "fileInstance.schema.json", but should it not point to the "image.schema.json" instead?

**Comment by aeidi89** [comment]
1. The way that both the "coordinateSpace.schema.json" and the "image.schema.json" is written ([on the wiki pages](https://github.com/HumanBrainProject/SANDS/wiki/SANDS-(v0.1))), yes.

**Comment by lzehl** [comment]
Then this can be corrected in the code accordingly. 
@UlrikeS91 : let me know if you have time, otherwise I'll put it on my list ;)

**Comment by aeidi89** [comment]
@lzehl: yes, you understood me correctly.

Then you get the indirect linking: `defaultImage` of _**coordinateSpace.schema.json**_ points to _**image.schema.json**_ which have `definedIn` that points to _**fileInstance.schema.json**_.

**Comment by lzehl** [comment]
todo:
- merge `axes.schema.json` #35  into `coordinateSpace.schema.json`

**Comment by UlrikeS91** [comment]
Revisions are finished.
