### ISSUE TITLE
controlledTerms - idea and implementation

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#41]
Within MINDS (v1/v2) we have/had a lot of schemas that hold only a "name" property (e.g., for species). The corresponding JSON-LDs in the KG should actually contain controlled terms that in the best case also link to an ontology (e.g., for species).

The discussion about optimizing this ended in a schema construct which is named "controlledTerms" which will for the KG only be created by curators, not by the user. The user can only reference to what is already in the KG in these cases.

The schemas of "controlledTerms" should always look the same from the structure point of view:
```json
{
  "$id": "https://schema.ebrains.eu/controlledTerms.schema.json",  
  "$schema": "http://json-schema.org/draft-07/schema#",  
  "description": "Schema to define controlled terms which can be linked to ontology terms.",  
  "type": "object",  
  "additionalProperties": false,  
  "properties": {
    "@type": {
      "type": "string",
      "description": "Metadata node type (schema).",
      "const": "https://schema.ebrains.eu/ControlledTerms",
    },
    "@id": {
      "type": "string",
      "description": "Metadata node identifier.",
      "pattern": "sands/controlledTerms/([A-Za-z0-9_-]+).json"
    },
    "name": {
      "type": "string",
      "description": "Controlled term originating from a defined terminology."
    },
    "relatedOntology": {
      "type": "string",
      "description": "Identifier of the related ontology that corresponds to the controlled term."
    }
  }
}
```

Now, for species this means that a JSON-LD could look like this, and could be referenced by the user with the corresponding `@id` (which is here a mock-up, based on what we have in the KG:
```json
{
 "@type": "https://schema.ebrains.eu/ControlledTerms",
 "@id": "https://schema.ebrains.eu/controlledTerms/species/0ea4e6ba-2681-4f7d-9fa9-49b915caaac9",
 "name": "homo sapiens",
 "relatedOntology": "NCBI:txid9606"
}
```

This is at least the basic idea. What needs to be discussed in this context: 
1) should the `@type` be more specific in the JSON-LDs, e.g. `"@type" : "https://schema.ebrains.eu/controlledTerms/Species"` for all json-LDs that define a species? can we provide these specific `"@type"`s in an enum?
2) is it possible to control the dependency between specific `"@type"` and `"name"` and `"relatedOntology"`? or do we trust the curator to make sure that this is consistent?
3) could we provide users the possibility to suggest such controlledTerms which then after a positive evaluation can be added to the KG?
4) should the relatedOntology be a link (URI/IRI) instead of an identifier? (@tgbugs how would that look like?)

In context with controlled terms we always have to keep in mind that we want to design a schema model that can be used outside of the KG, but when used in the KG has certain assumptions / restrictions.

Looking forward to questions and comments on this!

**Comment by tgbugs** [comment]
Make relatedOntology the fully expanded uri.

**Comment by UlrikeS91** [comment]
Based on recent discussions, the updated schema should look like this:

     {
       "$id": "https://openminds.ebrains.eu/sands/controlledTerms.schema.json",
       "$schema": "http://json-schema.org/draft-07/schema#",
       "description": "Schema to define controlled terms which can be linked to ontology terms.",
       "type": "object",
       "additionalProperties": false,   
       "required": [
         "@type",
         "@id",
         "name"
       ],
       "properties": {
         "@type": {
           "type": "string",
           "description": "Metadata node type (schema).",
           "const": "https://openminds.ebrains.eu/sands/controlledTerms"
         },
         "@id": {
           "type": "string",
           "description": "Metadata node identifier."
         },    
         "name": {
           "type": "string",
           "description": "Controlled term originating from a defined terminology."
         },
         "relatedOntology": {
           "type": "string",
           "description": "Identifier (IRI) to related ontological term.",
           "format": "iri"
         }
       }
     }

Based on #44, #48 and #49. 

@lzehl: I think you said that this should be its own repo. Does that mean that the schema will be in that repo then or only collect the JSON-LD there?

**Comment by UlrikeS91** [comment]
Update: The `controlledTerm` schema will be part of the openMINDS schemas. An additional repo will be made to collect the used JSON-LDs. 

Question @lzehl: The `$ref` in the SANDS schemas need to be updated to reflect this. There are 2 options: 
1) The SANDS `definitions.json` gets a definition `CONTROLLED_TERM` which in turn points to the openMINDS repo. 
2) The `$ref` in each SANDS schema, that uses `controlledTerm`, gets updated to point to the openMINDS `definitions.json`. 

I assume 2) is the better one/I like 2) better. Any preferences?

**Comment by lzehl** [comment]
I would say option 1 should be preferred, because we could do this for all references that point to openMINDS (also file and fileInstance, dataset and datasetVersion, +?).  
This way we have in each repository (or actually metadata model version) exactly one file where we need to maintain the refs: the definitions.json, which point to the raw-schemas (independent of where they are).

@UlrikeS91 Would you agree?

**Comment by UlrikeS91** [comment]
That's true. It would make the maintenance for all openMINDS objects easier, too. I'll do those updates in one big PR when Stefan has merged the last open PRs.

**Comment by UlrikeS91** [comment]
controlledTerms are solved differently now. This can be closed.
