### ISSUE TITLE
Entry type for "relatedOntology"

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#44]
@tgbugs : what entry type do we want to have for `relatedOntology` property?
Please see below for the more detailed questions

What was the previous way / what was discussed:
A) current status in the KG:
  - `relatedOntology` property expects `$ref` to KG ontology JSON-LD (specific type, e.g. `ontologies/core/organism/v1.0.0/xxx`)
  - this prevents to link to any ontology but the ontology terms that are integrated into the KG
B) discussed alternative:
  - `relatedOntology` property expects IRI/URI to ontological term (does this exist?) or the ontological identifier (is this enough for finding it)?
  - that way also ontologies could be referenced that are not yet integrated into the KG
  - link between what is integrated in the KG and the `relatedOntology` property entry would be indirect (but automatically established) using the IRI/URI or the ontological identifier (see questions above)

@tgbugs: 
1) Would you prefer *A)* over *B)* or *B)* over *A)*?
2) If you prefer *B)* would the entry be an IRI/URI or the ontological identifier?
    2.1) Could you give an example how these entries look like (what to expect / how to find them)?

**Comment by tgbugs** [comment]
Just use the IRI so that it is open. That way you can detect that the IRI has not been in ingested into KG.

**Comment by lzehl** [comment]
:+1:

**Comment by UlrikeS91** [comment]
> 👍 @UlrikeS91 once we go over the schemas again (also in openminds) let's just double check that this decision is implemented.

Okay, I'll probably go over most of the SANDS schemas today. Then I'll change the format back to IRI (instead of URI).

**Comment by UlrikeS91** [comment]
Decided for IRI based on some discussion related to openMINDS as well. Can be closed
