### ISSUE TITLE
pattern for `@id`

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#49]
@olinux how do we define the pattern for `@id` in SANDS (v0.1) and openMINDS (v3.0)?

Old way (MINDS v1.0 & uniMINDS v2.0, example a "parcellationatlas" plus the generalized pattern):  
- `"@id": "minds/core/parcellationatlas/v1.0.0/94c1125b-b87e-45e4-901c-00daee7f2579"`
- `"@id": "schemamodel/schemacategory/schemaname/v1.0.0/uniqueidentifier"`

How can we simplify this or make it more intuative for SANDS and openMINDS?  
1.  `"@id": "schemamodel/schemamodelversion/schemacategory/schemaname/uniqueidentifier"`
2.  `"@id": "schemamodel/schemamodelversion/schemaname/uniqueidentifier"`

For the schemamodel: should we group everything into openMINDS? e.g.,  
- `openminds/core_v1.0/schemacategory/...`  
- `openminds/core_v2.0/schemacategory/...`  
- `openminds/core_v3.0/schemacategory/...`  
- `openminds/sands_v0.1/schemacategory/...`  
[this part might be related to #48 as well]

This would mean that I get rid of "core" for the schema categories, because it would represent the tier1 metadata model in the openMINDS GitHub Repo, if we plan to merge all EBRAINS/HBP schemas in this repository.  
This would include the tier2 metadata model (sands) as well as the in-depth metadata models (??).
@apdavison : is this what you had in mind as well, when we discussed this last?

**Comment by lzehl** [comment]
`@id: "free text"`

**Comment by UlrikeS91** [comment]
Solved differently and can be closed
