### ISSUE TITLE
definition of origin

### ISSUE THREAD

**Issue by xgui3783** [HumanBrainProject/openMINDS_SANDS#8]
I know it was me who proposed to have origin as a field in SAND schema, but having a coordinate may be a self-referencing. 

For example, if a space defines the origin to be `[75,135,12]`, assuming um as unit, it is 75um, 135um, 12um from where? 

I wonder if the origin should be an enum (PIR origin of volume FILENAME.nii.gz) or an ontology (Weighted center of hippocampus)

**Comment by skoehnen** [comment]
The idea is that the image origin is in relation to the right-hand-rule.
A fixed coordinate space where the origin can be described.

**Comment by lzehl** [comment]
This is part of the "axes.schema.json". See #35

**Comment by UlrikeS91** [comment]
This is very outdated and I think fixed, too. I will close this issue.
