### ISSUE TITLE
Renaming/Reorganising SANDS repo

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_SANDS#83]
@lzehl mentioned this during the last meeting. The `@type` constant has been decided to be 

`@type: https://openminds.ebrains.eu/sands/schemaName` for SANDS and 
`@type: https://openminds.ebrains.eu/core/schemaName` for openMINDS (v3).

Since the openMINDS `@type` has "core" in it, we should rename the "core"-folder for SANDS to something else or re-organise the SANDS schemas into a different folder structure.

@aeidi89, @skoehnen, @lzehl and @blixilla: Any suggestions? 

My suggestions would be:

**Option 1**
SANDS/atlas/

     atlasTerminology.schema.json
     brainAtlas.schema.json
     brainAtlasVersion.schema.json
SANDS/main/ 

     anatomicalEntity.schema.json
     annotation.schema.json
     coordinateSpace.schema.json
     entityToEntity.schema.json
SANDS/elements/

     coordinatePoint.schema.json
     electrode.schema.json
     electrodeArray.schema.json
     electrodeContact.schema.json
     image.schema.json
SANDS/options/ 

     visualizationParameters.schema.json

******

**Option 2**
SANDS/atlas/

     atlasTerminology.schema.json
     brainAtlas.schema.json
     brainAtlasVersion.schema.json
SANDS/elements/ 

     anatomicalEntity.schema.json
     annotation.schema.json
     coordinatePoint.schema.json
     coordinateSpace.schema.json
     electrode.schema.json
     electrodeArray.schema.json
     electrodeContact.schema.json
     entityToEntity.schema.json
     image.schema.json
SANDS/options/ 

     visualizationParameters.schema.json

**Comment by lzehl** [comment]
@UlrikeS91 thanks for starting this issue.  
How about **option 3**?

SANDS/main/

    atlasTerminology.schema.json
    brainAtlas.schema.json
    brainAtlasVersion.schema.json
    coordinateSpace.schema.json
    annotation.schema.json
    anatomicalEntity.schema.json
    coordinatePoint.schema.json (might also go into elements)
    image.schema.json (might also go into elements)
    visualizationParameters.schema.json

SANDS/elements/

    electrode.schema.json
    electrodeArray.schema.json
    electrodeContact.schema.json
    etc.

**Comment by lzehl** [comment]
Or **option 4** no sub-categories: everything is just under SANDS directly.

**Comment by skoehnen** [comment]
I am not sure, what would be the advantages of organizing SANDS in sub-categories.

At the moment I would be in favor of a flat structure like **option 4**.

**Comment by lzehl** [comment]
I prefer **option 4** as well :wink:

**Comment by UlrikeS91** [comment]
The way SANDS is right now, I also think option 4 is the best. We just need to keep in mind that it will grow, and then it may become a bit chaotic. Anyway, I would love to give option 4 a try. The fewer levels the better :)

**Comment by lzehl** [comment]
Based on the feedback here and in the SANDS meeting (Oct 27) the following was decided:
- option 4 (no subdivision)

**Comment by lzehl** [comment]
@UlrikeS91 will take over the PR for this

**Comment by UlrikeS91** [comment]
Fixed and merged with #94
