### ISSUE TITLE
schema-revision: core/visualizationParameters.schema.json 

### ISSUE THREAD

**Issue by UlrikeS91** [HumanBrainProject/openMINDS_SANDS#84]
@aeidi89 and I have discussed all parts of SANDS and couldn't quite figure out how to interpret `visualizationParameters` correctly. This may be cause din parts by the structural changes to other parts of SANDS, but already when I updated the `visualizationParameters.schema.json` (see #70) that something was a bit confusing. 

My original question in that PR was: 
"Something in `definedIn` doesn't make sense. Is it really supposed to point to an `image`? What image would that be? And if it should point to an image, the description is wrong, right?"

This was 15 days ago and I kind of forgot about it, but talking to @aeidi89 now again, we asked ourselves the same question. 

To us, it would be nice if the `visualizationParameters` could be recyclable within a `brainAtlas`. For example, a brain region could have remained unchanged from one version to the other (e.g. hippocampal region from WHS v2 to v3). As the schemas are right now, we would need to make 2 annotations (one per version) which have 2 different visualization parameters, but technically neither the annotation nor the visualization parameters have changed between the versions. 
Following this example, wouldn't it make more sense to have the `interalIdentifier` and the `definedIn` from the `visualizationParameters` moved up to the `annotation` instead? Then for the WHS example, we would make 2 annotations (which is necessary anyway to be able to link it to `brainAtlasVersion`), but could recycle the `visualizationParameters` for both.

**Comment by lzehl** [comment]
This comes back to two questions if an annotation is only defined in one file.  
Last time we discussed this, this was answered with "no it might not be". If we assume multiple files (e.g., annotations stored in two different resolutions) the internal identifier of the annotation also might differ between those files. 

We could also just make it simple and hope the above case never arises and assume for now that an annotation can only be defined in exactly one file with one bestViewPoint and Angle and one internal identifier. 

Note: Annotations can be reused between BrainAtlasVersions. But if an annotation changes it automatically defines a new BrainAtlasVersion.

**Comment by UlrikeS91** [comment]
Conclusion during SANDS meeting:

--> move all properties to `annotation.schema.json` (therefore remove `visualizationParameters.schema.json`)
--> `definedIn` either needs to point to `fileInstance` (to be consistent within `defindeIn`) OR needs to be renamed to e.g. `visualizedIn` to point to `image` (check all schemas expecting `image` if this is possible) 

(---> probably `visualizedIn` will be the prefered version)

**Comment by UlrikeS91** [comment]
Fixed and merged with #94
