### ISSUE TITLE
Replace "$ref"

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_SANDS#90]
Planned: 
To enable/facilitate the validation of an individual json against the used json-schema, we'll replace all `"$ref"` references:
```
   ...
   "linkToOtherSchema": {
      "description": "Link to another entity of type OtherSchema.",
      "$ref": "https://raw.githubusercontent.com/HumanBrainProject/openMINDS/master/v3.0/definitions.json#definitions/OTHER_SCHEMA"
   },
   ...
```
with the following:
```
   ...
   "linkToOtherSchema": {
      "type": "object",
      "description": "Link to another entity of type OtherSchema.",
      "$linkedType": "https://openminds.ebrains.eu/core/OtherSchema"
   },
   ...
```

This is based on a discussion and decision I made with @olinux .  
This change will also lead to the point that we are not gonna maintain a definitions.json anymore.

The example for arrays will follow soon. @olinux : this should look a bit different correct? using the array/items/oneOff keys?

**Comment by UlrikeS91** [comment]
Fixed and merged with #94
